from pulp import *
from .config_api import request_ai
import re

# Result dictionary
_result = {
    "success": False,
    "variables": {},
    "of": None,
    "of_value": None,
    "of_type": None,
    "constraints": [],
    "parts": []
}

# Result getter
def get_result() -> dict:
    return _result

def solve_linear_problem() -> dict:
    global _result

    # How the response should be like: 
    # {LpMaximize, 50*x+30*y, x;y, 4*x+2*y<=100;3*x+2*y<=90;y>=10}
    response = request_ai()

    # Check if follows the pattern {   }
    response = response.strip()
    if response.startswith("{") and not response.endswith("}"):
        response += "}"
    if not response.startswith("{") or not response.endswith("}"):
        _result = {"success": False, "error": response}
        return _result

    # Check if the problem is valid
    if response == "{}":
        _result = {
            "success": False,
            "error": "This doesn't seem to be a Linear Programming problem"
        }
        return _result

    try:
        no_keys = response.strip("{}").strip() # Remove {}
        parts = [p.strip() for p in no_keys.split(",", 3)]  # Split into 4 parts using ,

        if len(parts) != 4:
            _result = {
                "success": False,
                "error": "AI's answer is wrong. Try again"
            }
            return _result

        function_objective = parts[0] # "LpMaximize or LpMinimize"

        if function_objective not in ("LpMaximize", "LpMinimize"):
            _result = {
                "success": False,
                "error": f"Invalid objective type '{function_objective}'. Try again"
            }
            return _result

        function_objective_type = LpMaximize if function_objective == "LpMaximize" else LpMinimize
        prob = LpProblem("Problem", function_objective_type)

        # Variables
        variables_str = parts[2].split(";")  # Ex: ["x", "y"]

        # Validate variable names before creating them
        invalid_var_names = [v for v in variables_str if not re.match(r'^\w+$', v.strip())]
        if invalid_var_names:
            _result = {
                "success": False,
                "error": f"Invalid variable names generated by AI: {invalid_var_names}. Try again"
            }
            return _result

        variables = {}
        for v in variables_str:
            variables[v.strip()] = LpVariable(v.strip(), 0)

        # Validate objective function contains only safe characters before eval
        safe_obj_pattern = re.compile(r'^[\d\w\s\*\+\-\.]+$')
        if not safe_obj_pattern.match(parts[1]):
            _result = {
                "success": False,
                "error": f"Invalid objective function generated by AI: '{parts[1]}'. Try again"
            }
            return _result

        # Objective Function
        prob += eval(parts[1], {"__builtins__": {}}, variables), "obj"  # Ex: "50*x+30*y"

        # Constraints
        constraints = parts[3].split(";")  # Ex: ["4*x+2*y<=100", "3*x+2*y<=90", "y>=10"]

        # Remove x>=0, y>=0 generated by AI
        constraints = [
            c for c in constraints
            if not re.match(r'^\s*\w+\s*>=\s*0\s*$', c)
        ]

        # Validate constraint expressions contain only safe characters before eval
        safe_constraint_pattern = re.compile(r'^[\d\w\s\*\+\-\.\<\>=]+$')

        for k, c in enumerate(constraints, 1):
            if not safe_constraint_pattern.match(c):
                _result = {
                    "success": False,
                    "error": f"Invalid AI-generated constraint: '{c}'. Try again"
                }
                return _result

            match = re.search(r'(<=|>=|=)(.*)$', c)
            if not match or match.group(2).strip() == "":
                _result = {
                    "success": False,
                    "error": f"Invalid AI-generated constraint: '{c}'. Try again"
                }
                return _result

            prob += eval(c, {"__builtins__": {}}, variables), f"r{k}"

        prob.solve()

        _result = {
            "success": True,
            "variables": {v.name: v.value() for v in prob.variables()}, # Ex: {"x": 10.0, "y": 20.0}
            "of": prob.objective, # Ex: "50*x+30*y"
            "of_value": value(prob.objective), # Ex: 800.0 
            "of_type": parts[0], # Ex: "LpMaximize"
            "constraints": constraints, # Ex: ["4*x+2*y<=100", "3*x+2*y<=90", "y>=10"]
            "parts": parts
        }
        return _result

    except Exception:
        _result = {
            "success": False,
            "error": "AI's answer is wrong. Try again"
        }
        return _result